version: "3.9"
services:
  api:
    build: ./api
    environment:
      - NODE_ENV=production
      - PORT=4000
      - DATABASE_URL=file:./dev.db
      - REPORTS_STORAGE=local
      - REPORTS_DIR=/app/storage/reports
      - CORS_ORIGIN=*
    volumes:
      - api_data:/app/prisma
      - reports_data:/app/storage/reports
    ports:
      - "4000:4000"

  web:
    build: ./web
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  api_data:
  reports_data:
