version: "3.9"
services:
  api:
    build: ./api
    environment:
      - NODE_ENV=production
      - PORT=4000
      - DATABASE_URL=file:./prisma/dev.db
      - REPORTS_STORAGE=local
      - REPORTS_DIR=/app/storage/reports
      - CORS_ORIGIN=*
      - ADMIN_ENABLED=true
      - ADMIN_TOKEN=b8f2a9f3d1e94f35b0c1e6b9a7c2d4e8f1a3b5c7d9e0f2a4b6c8d0e1f3a5b7c9
    volumes:
      - api_data:/app/prisma
      - reports_data:/app/storage/reports
    ports:
      - "4000:4000"

  web:
    build: ./web
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  api_data:
  reports_data:
